Repository Volgarenok/spbspu-labs-2025-tp-a, pull requests merged in 2025-03, with the labels that each got.

#50 sherkunov.daniil/T0
  sherkunov.daniil/T0/main.cpp
Labels: fine, new gr 4

#84 holodilov.artem/T0
  holodilov.artem/T0/main.cpp
Labels: fine, new gr 5

#81 tarasova.julia/T0
  tarasova.julia/T0/main.cpp
Labels: fine, new gr 6

#85 nikonov.andrew/T0
  nikonov.andrew/T0/main.cpp
Labels: fine, gr 4
