Repository Volgarenok/spbspu-labs-2025-tp-a, pull requests merged in 2025-02, with the labels that each got.

#1 alymova.ksenia/T0
  alymova.ksenia/T0/main.cpp
Labels: fine, gr 4

#2 savintsev.ilya/T0
  savintsev.ilya/T0/main.cpp
Labels: fine, gr 4

#3 maslevtsov.stanislav/T0
  maslevtsov.stanislav/T0/main.cpp
Labels: fine, gr 4

#4 averenkov.eugene/T0
  averenkov.eugene/T0/main.cpp
Labels: fine, gr 5

#5 duhanina.alina/T0
  duhanina.alina/T0/main.cpp
Labels: fine, gr 5

#6 abramov.vladislav/T0
  abramov.vladislav/T0/main.cpp
Labels: fine, gr 4

#7 kiselev.sergey/T0
  kiselev.sergey/T0/main.cpp
Labels: fine, gr 5

#10 kushekbaev.danil/T0
  kushekbaev.danil/T0/main.cpp
Labels: fine, gr 1

#11 cherkasov.nikita/T0
  cherkasov.nikita/T0/main.cpp
Labels: fine, gr 4

#12 petrov.nikita/T0
  petrov.nikita/T0/main.cpp
Labels: fine, gr 1

#13 demehin.maxim/T0
  demehin.maxim/T0/main.cpp
Labels: fine, gr 5

#14 komarova.anastasia/T0
  komarova.anastasia/T0/main.cpp
Labels: fine, gr 4

#8 ohantsev.vladimir/T0
  ohantsev.vladimir/T0/main.cpp
Labels: fine, new gr 5

#15 krylov.matvey/T0
  krylov.matvey/T0/main.cpp
Labels: fine, gr 4

#16 karnauhova.alexandra/T0
  karnauhova.alexandra/T0/main.cpp
Labels: fine, gr 5

#18 mozhegova.maria/T0
  mozhegova.maria/T0/main.cpp
Labels: fine, gr 1

#19 aleksandrov.igor/T0
  aleksandrov.igor/T0/main.cpp
Labels: fine, gr 4

#20 rychkov.mihail/T0
  rychkov.mihail/T0/main.cpp
Labels: fine, gr 1

#21 trukhanov.mikhail/T0
  trukhanov.mikhail/T0/main.cpp
Labels: fine, new gr 6

#24 maslov.aleksey/T0
  maslov.aleksey/T0/main.cpp
Labels: fine, gr 1

#25 hismatova.elizaveta/T0
  hismatova.elizaveta/T0/main.cpp
Labels: fine, gr 1

#27 dirti.aldyn/T0
  dirti.aldyn/T0/main.cpp
Labels: fine, gr 5

#28 evstyunichev.konstantin/T0
  evstyunichev.konstantin/T0/main.cpp
Labels: fine, gr 5

#29 asafov.andrew/T0
  asafov.andrew/T0/main.cpp
Labels: fine, gr 4

#30 dribas.sergey/T0
  dribas.sergey/T0/main.cpp
Labels: fine, gr 5

#22 shapkov.gordey/T0
  shapkov.gordey/T0/main.cpp
Labels: fine, new gr 5

#40 nikonov.andrew/T0
  nikonov.andrew/main.cpp
Labels: fine, gr 4

#38 orlova.alena/T0
  orlova.alena/T0/main.cpp
Labels: fine, new gr 4

#35 kazak.egor/T0
  kazak.egor/T0/main.cpp
Labels: fine, new gr 4

#43 tkach.danil/T0
  tkach.danil/T0/main.cpp
Labels: fine, gr 1

#33 klimova.arina/T0
  klimova.arina/T0/main.cpp
Labels: fine, new gr 4

#39 shak.vitalina/T0
  shak.vitalina/T0/main.cpp
Labels: fine, new gr 6

#46 horoshilov.feodor/T0
  horoshilov.feodor/T0/main.cpp
Labels: fine, new gr 5

#51 zakirov.marat/T0
  zakirov.marat/T0/main.cpp
Labels: fine, gr 4

#36 puzikov.herman/T0
  puzikov.herman/T0/main.cpp
Labels: fine, new gr 6, comedy artist

#55 kizhin.evgeniy/T0
  kizhin.evgeniy/T0/main.cpp
Labels: fine, gr 5

#56 zholobov.oleg/T0
  zholobov.oleg/T0/main.cpp
Labels: fine, gr 5

#37 filonova.angelina/T0
  filonova.angelina/T0/main.cpp
Labels: fine, new gr 6

#57 smirnov.alexandr/T0
  smirnov.alexandr/T0/main.cpp
Labels: fine, gr 1

#53 nehvedovich.anastasiya/t0
  nehvedovich.anastasiya/T0/main.cpp
Labels: fine, new gr 6

#48 shiryaeva.daria/T0
  shiryaeva.daria/T0/main.cpp
Labels: fine, new gr 6

#49 pilugina.margarita/T0
  pilugina.margarita/T0/main.cpp
Labels: fine, new gr 6

#58 maslovskiy.vladislav/T0
  maslovskiy.vladislav/T0/main.cpp
Labels: fine, gr 4

#67 finaev.alexey/T0
  finaev.alexey/T0/main.cpp
Labels: fine, gr 1

#66 belobrov.timofey/T0
  belobrov.timofey/T0/main.cpp
Labels: fine, gr 4

#65 sharifullina.sofia/T0
  sharifullina.sofia/T0/main.cpp
Labels: fine, gr 1

#61 gavrilova.polina/T0
  gavrilova.polina/T0/main.cpp
Labels: fine, gr 5

#32 khokhryakova.daria/T0
  khokhryakova.daria/T0/main.cpp
Labels: fine, new gr 5

#69 ageev.ilya/T0
  ageev.ilya/T0/main.cpp
Labels: fine, new gr 4

#26 elagin.sergey/T0
  elagin.sergey/T0
Labels: fine, new gr 4

#76 guseynov.guseyn/T0
  guseynov.guseyn/T0/main.cpp
Labels: fine, gr 1

#59 milchevskiy.vladislave/T0
  milchevskiy.vladislave/T0/main.cpp
Labels: fine, new gr 6

#45 belyaev.veniamin/T0
  belyaev.veniamin/T0/main.cpp
Labels: fine, new gr 4

#60 shchadilov.arseniy/T0
  shchadilov.arseniy/T0/main.cpp
Labels: fine, new gr 5

#70 kurbyko.aleksey/T0
  kurbyko.aleksey/T0/main.cpp
Labels: fine, new gr 5

#78 lebedev.alexandr/T0
  lebedev.alexandr/T0/main.cpp
Labels: fine, gr 1

#77 lanovenko.ivan/T0
  lanovenko.ivan/T0/main.cpp
Labels: fine, gr 1

#71 mazitov.vladislav/T0
  mazitov.vladislav/T0/main.cpp
Labels: fine, new gr 6

#80 kharlamov.kirill/T0
  kharlamov.kirill/T0/main.cpp
Labels: fine, new gr 5
