Repository Volgarenok/spbspu-labs-2025-tp-a, pull requests merged in 2025-05, with the labels that each got.

#99 alymova.ksenia/T2
  alymova.ksenia/T2/main.cpp
  alymova.ksenia/T2/stream-guard.cpp
  alymova.ksenia/T2/stream-guard.hpp
  alymova.ksenia/T2/structs.cpp
  alymova.ksenia/T2/structs.hpp
Labels: fine, gr 4

#142 mozhegova.maria/T2
  mozhegova.maria/T2/dataStruct.cpp
  mozhegova.maria/T2/dataStruct.hpp
  mozhegova.maria/T2/main.cpp
  mozhegova.maria/T2/scopeGuard.cpp
  mozhegova.maria/T2/scopeGuard.hpp
Labels: fine, gr 1

#93 kiselev.sergey/T2
  kiselev.sergey/T2/data.cpp
  kiselev.sergey/T2/data.hpp
  kiselev.sergey/T2/main.cpp
  kiselev.sergey/T2/scopeGuard.cpp
  kiselev.sergey/T2/scopeGuard.hpp
Labels: fine, gr 5

#97 kizhin.evgeniy/T2
  kizhin.evgeniy/T2/data-struct-input.cpp
  kizhin.evgeniy/T2/data-struct-less.cpp
  kizhin.evgeniy/T2/data-struct-output.cpp
  kizhin.evgeniy/T2/data-struct.hpp
  kizhin.evgeniy/T2/main.cpp
  kizhin.evgeniy/T2/stream-guard.cpp
  kizhin.evgeniy/T2/stream-guard.hpp
Labels: fine, gr 5

#148 drai.mohamedamine/T0
  drai.mohamedamine/T0/main.cpp
Labels: fine, new gr 5

#161 beshimow.meylis/T0
  beshimow.meylis/T0/main.cpp
Labels: gr 5

#87 ohantsev.vladimir/T2
  ohantsev.vladimir/T2/data.cpp
  ohantsev.vladimir/T2/data.h
  ohantsev.vladimir/T2/main.cpp
  ohantsev.vladimir/common/delimiter.cpp
  ohantsev.vladimir/common/delimiter.h
  ohantsev.vladimir/common/iofmtguard.cpp
  ohantsev.vladimir/common/iofmtguard.h
Labels: fine, new gr 5

#89 demehin.maxim/T2
  demehin.maxim/T2/data_struct.cpp
  demehin.maxim/T2/data_struct.hpp
  demehin.maxim/T2/main.cpp
  demehin.maxim/common/delimiter.cpp
  demehin.maxim/common/delimiter.hpp
  demehin.maxim/common/scope_guard.cpp
  demehin.maxim/common/scope_guard.hpp
Labels: fine, gr 5

#103 savintsev.ilya/T2
  savintsev.ilya/T2/data-struct.cpp
  savintsev.ilya/T2/data-struct.hpp
  savintsev.ilya/T2/io-utils.cpp
  savintsev.ilya/T2/io-utils.hpp
  savintsev.ilya/T2/main.cpp
  savintsev.ilya/T2/scope-guard.cpp
  savintsev.ilya/T2/scope-guard.hpp
Labels: fine, gr 4

#100 maslevtsov.stanislav/T2
  maslevtsov.stanislav/T2/compare.cpp
  maslevtsov.stanislav/T2/compare.hpp
  maslevtsov.stanislav/T2/data_struct.cpp
  maslevtsov.stanislav/T2/data_struct.hpp
  maslevtsov.stanislav/T2/io_fmt_guard.cpp
  maslevtsov.stanislav/T2/io_fmt_guard.hpp
  maslevtsov.stanislav/T2/main.cpp
Labels: fine, gr 4

#98 filonova.angelina/T2
  filonova.angelina/T2/data_struct.cpp
  filonova.angelina/T2/data_struct.hpp
  filonova.angelina/T2/format_guard.cpp
  filonova.angelina/T2/format_guard.hpp
  filonova.angelina/T2/input_struct.cpp
  filonova.angelina/T2/input_struct.hpp
  filonova.angelina/T2/main.cpp
Labels: fine, new gr 6

#109 duhanina.alina/T2
  duhanina.alina/T2/dataStruct.cpp
  duhanina.alina/T2/dataStruct.hpp
  duhanina.alina/T2/main.cpp
Labels: fine, gr 5

#113 aleksandrov.igor/T2
  aleksandrov.igor/T2/data-struct.cpp
  aleksandrov.igor/T2/data-struct.hpp
  aleksandrov.igor/T2/input-struct.cpp
  aleksandrov.igor/T2/input-struct.hpp
  aleksandrov.igor/T2/main.cpp
  aleksandrov.igor/T2/output-struct.cpp
  aleksandrov.igor/T2/output-struct.hpp
  aleksandrov.igor/T2/stream-guard.cpp
  aleksandrov.igor/T2/stream-guard.hpp
Labels: fine, gr 4

#133 evstyunichev.konstantin/T2
  evstyunichev.konstantin/T2/data_struct.cpp
  evstyunichev.konstantin/T2/data_struct.hpp
  evstyunichev.konstantin/T2/main.cpp
  evstyunichev.konstantin/T2/stream_guard.cpp
  evstyunichev.konstantin/T2/stream_guard.hpp
Labels: fine, gr 5

#88 dribas.sergey/T2
  dribas.sergey/T2/data.cpp
  dribas.sergey/T2/data.hpp
  dribas.sergey/T2/main.cpp
  dribas.sergey/common/delimiter.cpp
  dribas.sergey/common/delimiter.hpp
  dribas.sergey/common/streamGuard.cpp
  dribas.sergey/common/streamGuard.hpp
Labels: fine, gr 5

#94 shapkov.gordey/T2
  shapkov.gordey/T2/dataStruct.cpp
  shapkov.gordey/T2/dataStruct.hpp
  shapkov.gordey/T2/iomanipulators.cpp
  shapkov.gordey/T2/iomanipulators.hpp
  shapkov.gordey/T2/main.cpp
  shapkov.gordey/common/delimiter.cpp
  shapkov.gordey/common/delimiter.hpp
  shapkov.gordey/common/scopeGuard.cpp
  shapkov.gordey/common/scopeGuard.hpp
Labels: fine, new gr 5

#105 maslov.aleksey/T2
  maslov.aleksey/T2/dataStruct.cpp
  maslov.aleksey/T2/dataStruct.hpp
  maslov.aleksey/T2/ioTypes.cpp
  maslov.aleksey/T2/ioTypes.hpp
  maslov.aleksey/T2/main.cpp
  maslov.aleksey/T2/streamGuard.cpp
  maslov.aleksey/T2/streamGuard.hpp
Labels: fine, gr 1

#131 Mezentsev.anton/t2
  mezentsev.anton/T2/data.cpp
  mezentsev.anton/T2/data.h
  mezentsev.anton/T2/guard.cpp
  mezentsev.anton/T2/guard.h
  mezentsev.anton/T2/main.cpp
Labels: fine, new gr 5

#125 kharlamov.kirill/T2
  kharlamov.kirill/T2/data.cpp
  kharlamov.kirill/T2/data.h
  kharlamov.kirill/T2/guard.cpp
  kharlamov.kirill/T2/guard.h
  kharlamov.kirill/T2/main.cpp
Labels: fine, new gr 5

#106 kushekbaev.danil/T2
  kushekbaev.danil/T2/datastruct.cpp
  kushekbaev.danil/T2/datastruct.hpp
  kushekbaev.danil/T2/main.cpp
  kushekbaev.danil/common/streamguard.cpp
  kushekbaev.danil/common/streamguard.hpp
Labels: fine, gr 4

#128 belyaev.veniamin/T2
  belyaev.veniamin/T2/data-struct.cpp
  belyaev.veniamin/T2/data-struct.hpp
  belyaev.veniamin/T2/io-helpers.cpp
  belyaev.veniamin/T2/io-helpers.hpp
  belyaev.veniamin/T2/main.cpp
  belyaev.veniamin/T2/stream-guard.cpp
  belyaev.veniamin/T2/stream-guard.hpp
Labels: fine, new gr 4

#129 tkach.danil/T2
  tkach.danil/T2/data_struct.hpp
  tkach.danil/T2/io_actions.cpp
  tkach.danil/T2/io_actions.hpp
  tkach.danil/T2/main.cpp
  tkach.danil/T2/streamguard.cpp
  tkach.danil/T2/streamguard.hpp
Labels: fine, gr 1

#111 kostyukov.mikhail/T2
  kostyukov.mikhail/T2/dataStruct.cpp
  kostyukov.mikhail/T2/dataStruct.hpp
  kostyukov.mikhail/T2/main.cpp
  kostyukov.mikhail/T2/scopeGuard.cpp
  kostyukov.mikhail/T2/scopeGuard.hpp
Labels: fine, new gr 5

#170 Kalmbah.mihail/T0
  kalmbah.mihail/T0/main.cpp
Labels: fine, gr 4

#121 petrov.nikita/T2
  petrov.nikita/T2/data_struct.cpp
  petrov.nikita/T2/data_struct.hpp
  petrov.nikita/T2/main.cpp
Labels: fine, gr 1

#150 orlova.alena/T2
  orlova.alena/T2/DataStruct.cpp
  orlova.alena/T2/DataStruct.h
  orlova.alena/T2/main.cpp
Labels: fine, new gr 4

#140 trukhanov.mikhail/T2
  trukhanov.mikhail/T2/data_input.cpp
  trukhanov.mikhail/T2/data_input.hpp
  trukhanov.mikhail/T2/data_struct.cpp
  trukhanov.mikhail/T2/data_struct.hpp
  trukhanov.mikhail/T2/main.cpp
  trukhanov.mikhail/T2/stream_guard.cpp
  trukhanov.mikhail/T2/stream_guard.hpp
Labels: fine, new gr 6

#138 klimova.arina/T2
  klimova.arina/T2/datastruct.cpp
  klimova.arina/T2/datastruct.hpp
  klimova.arina/T2/iofmtguard.cpp
  klimova.arina/T2/iofmtguard.hpp
  klimova.arina/T2/main.cpp
Labels: fine, new gr 4

#114 shiryaeva.daria/T2
  shiryaeva.daria/T2/data_struct.cpp
  shiryaeva.daria/T2/data_struct.hpp
  shiryaeva.daria/T2/format_guard.cpp
  shiryaeva.daria/T2/format_guard.hpp
  shiryaeva.daria/T2/input_struct.cpp
  shiryaeva.daria/T2/input_struct.hpp
  shiryaeva.daria/T2/main.cpp
Labels: fine, new gr 6
