Repository Volgarenok/spbspu-labs-2025-tp-a, pull requests merged in 2025-06, with the labels that each got.

#174 maslevtsov.stanislav/T3
  maslevtsov.stanislav/T2/data_struct.cpp
  maslevtsov.stanislav/T3/calc_areas.cpp
  maslevtsov.stanislav/T3/calc_areas.hpp
  maslevtsov.stanislav/T3/count.cpp
  maslevtsov.stanislav/T3/count.hpp
  maslevtsov.stanislav/T3/echo_rmecho.cpp
  maslevtsov.stanislav/T3/echo_rmecho.hpp
  maslevtsov.stanislav/T3/find_max_min.cpp
  maslevtsov.stanislav/T3/find_max_min.hpp
  maslevtsov.stanislav/T3/main.cpp
  maslevtsov.stanislav/T3/polygon_utils.cpp
  maslevtsov.stanislav/T3/polygon_utils.hpp
  maslevtsov.stanislav/T3/shapes.cpp
  maslevtsov.stanislav/T3/shapes.hpp
  maslevtsov.stanislav/common/io_fmt_guard.cpp
  maslevtsov.stanislav/common/io_fmt_guard.hpp
Labels: gr 4

#126 pilugina.margarita/T2
  pilugina.margarita/T2/data_struct.cpp
  pilugina.margarita/T2/data_struct.hpp
  pilugina.margarita/T2/format_guard.cpp
  pilugina.margarita/T2/format_guard.hpp
  pilugina.margarita/T2/format_wrapper.cpp
  pilugina.margarita/T2/format_wrapper.hpp
  pilugina.margarita/T2/main.cpp
  pilugina.margarita/T2/utils.cpp
  pilugina.margarita/T2/utils.hpp
Labels: fine, new gr 6

#90 gavrilova.polina/T2
  gavrilova.polina/T2/DataStruct.cpp
  gavrilova.polina/T2/DataStruct.hpp
  gavrilova.polina/T2/IOStreamGuard.cpp
  gavrilova.polina/T2/IOStreamGuard.hpp
  gavrilova.polina/T2/main.cpp
Labels: fine, gr 5, comedy artist

#127 horoshilov.feodor/T2
  horoshilov.feodor/T2/data.cpp
  horoshilov.feodor/T2/data.h
  horoshilov.feodor/T2/main.cpp
  horoshilov.feodor/common/Delimiter.cpp
  horoshilov.feodor/common/Delimiter.h
  horoshilov.feodor/common/Guard.cpp
  horoshilov.feodor/common/Guard.h
Labels: fine, new gr 5

#110 khokhryakova.daria/T2
  khokhryakova.daria/T2/DataStruct.cpp
  khokhryakova.daria/T2/DataStruct.h
  khokhryakova.daria/T2/main.cpp
Labels: new gr 5

#178 Bocharov.egor/T2
  bocharov.egor/T2/dataStruct.cpp
  bocharov.egor/T2/dataStruct.hpp
  bocharov.egor/T2/ioTypes.cpp
  bocharov.egor/T2/ioTypes.hpp
  bocharov.egor/T2/main.cpp
  bocharov.egor/common/ioDelimiter.cpp
  bocharov.egor/common/ioDelimiter.hpp
  bocharov.egor/common/streamGuard.cpp
  bocharov.egor/common/streamGuard.hpp
Labels: fine, gr 5

#134 Brevnov.nikita/t2
  brevnov.nikita/T2/data_struct.cpp
  brevnov.nikita/T2/data_struct.hpp
  brevnov.nikita/T2/main.cpp
Labels: fine, gr 5

#173 tkach.danil/T3
  tkach.danil/T2/io_actions.cpp
  tkach.danil/T2/io_actions.hpp
  tkach.danil/T2/main.cpp
  tkach.danil/T3/commands.cpp
  tkach.danil/T3/commands.hpp
  tkach.danil/T3/main.cpp
  tkach.danil/T3/shapes.cpp
  tkach.danil/T3/shapes.hpp
  tkach.danil/common/common_io_actions.cpp
  tkach.danil/common/common_io_actions.hpp
  tkach.danil/common/streamguard.cpp
  tkach.danil/common/streamguard.hpp
Labels: fine, gr 1

#176 kizhin.evgeniy/T3
  kizhin.evgeniy/T2/data-struct-input.cpp
  kizhin.evgeniy/T2/data-struct-output.cpp
  kizhin.evgeniy/T3/command-processor.cpp
  kizhin.evgeniy/T3/command-processor.hpp
  kizhin.evgeniy/T3/main.cpp
  kizhin.evgeniy/T3/polygon.cpp
  kizhin.evgeniy/T3/polygon.hpp
  kizhin.evgeniy/common/interim-input-utils.cpp
  kizhin.evgeniy/common/interim-input-utils.hpp
  kizhin.evgeniy/common/stream-guard.cpp
  kizhin.evgeniy/common/stream-guard.hpp
Labels: fine, gr 5

#158 shapkov.gordey/T3
  shapkov.gordey/T3/GeometricalTypes.cpp
  shapkov.gordey/T3/GeometricalTypes.hpp
  shapkov.gordey/T3/cmds.cpp
  shapkov.gordey/T3/cmds.hpp
  shapkov.gordey/T3/main.cpp
  shapkov.gordey/T3/polygonfunctors.cpp
  shapkov.gordey/T3/polygonfunctors.hpp
Labels: fine, new gr 5

#151 ohantsev.vladimir/T3
  ohantsev.vladimir/T3/cmds_run.cpp
  ohantsev.vladimir/T3/cmds_run.h
  ohantsev.vladimir/T3/main.cpp
  ohantsev.vladimir/T3/polygon.cpp
  ohantsev.vladimir/T3/polygon.h
  ohantsev.vladimir/T3/polygon_cmds.cpp
  ohantsev.vladimir/T3/polygon_cmds.h
  ohantsev.vladimir/common/command_handler.cpp
  ohantsev.vladimir/common/command_handler.h
Labels: fine, new gr 5

#137 lanovenko.ivan/T2
  lanovenko.ivan/T2/data_struct.cpp
  lanovenko.ivan/T2/data_struct.hpp
  lanovenko.ivan/T2/main.cpp
  lanovenko.ivan/common/delimiter.cpp
  lanovenko.ivan/common/delimiter.hpp
  lanovenko.ivan/common/scope_guard.cpp
  lanovenko.ivan/common/scope_guard.hpp
Labels: fine, gr 1

#144 sveshnikov.michail/T2
  sveshnikov.michail/T2/data-struct.cpp
  sveshnikov.michail/T2/data-struct.hpp
  sveshnikov.michail/T2/main.cpp
  sveshnikov.michail/T2/stream-guard.cpp
  sveshnikov.michail/T2/stream-guard.hpp
Labels: fine, gr 4

#143 finaev.alexey/T2
  finaev.alexey/T2/dataStruct.hpp
  finaev.alexey/T2/ioData.cpp
  finaev.alexey/T2/ioData.hpp
  finaev.alexey/T2/main.cpp
  finaev.alexey/T2/sortDataVector.cpp
  finaev.alexey/T2/sortDataVector.hpp
  finaev.alexey/common/delimiter.cpp
  finaev.alexey/common/delimiter.hpp
  finaev.alexey/common/streamGuard.cpp
  finaev.alexey/common/streamGuard.hpp
Labels: fine, gr 1

#162 drai.mohamedamine/T2
  drai.mohamedamine/T2/data.cpp
  drai.mohamedamine/T2/data.hpp
  drai.mohamedamine/T2/io.cpp
  drai.mohamedamine/T2/io.hpp
  drai.mohamedamine/T2/main.cpp
  drai.mohamedamine/T2/stream_guard.cpp
  drai.mohamedamine/T2/stream_guard.hpp
Labels: fine, new gr 5

#119 zakirov.marat/T2
  zakirov.marat/T2/main.cpp
  zakirov.marat/T2/processing_structures.cpp
  zakirov.marat/T2/processing_structures.hpp
  zakirov.marat/T2/stream_guardian.cpp
  zakirov.marat/T2/stream_guardian.hpp
Labels: fine, gr 4

#155 fedorova.ksenia/T2
  fedorova.ksenia/T2/DataStruct.cpp
  fedorova.ksenia/T2/DataStruct.h
  fedorova.ksenia/T2/main.cpp
Labels: fine, new gr 4, comedy artist

#156 dribas.sergey/T3
  dribas.sergey/T3/main.cpp
  dribas.sergey/T3/polygon.cpp
  dribas.sergey/T3/polygon.hpp
  dribas.sergey/T3/printCmd.cpp
  dribas.sergey/T3/printCmd.hpp
Labels: fine, gr 5, comedy artist

#171 kostyukov.mikhail/T3
  kostyukov.mikhail/T2/dataStruct.cpp
  kostyukov.mikhail/T2/dataStruct.hpp
  kostyukov.mikhail/T3/commandProcessor.cpp
  kostyukov.mikhail/T3/commandProcessor.hpp
  kostyukov.mikhail/T3/commands.cpp
  kostyukov.mikhail/T3/commands.hpp
  kostyukov.mikhail/T3/geometry.cpp
  kostyukov.mikhail/T3/geometry.hpp
  kostyukov.mikhail/T3/main.cpp
  kostyukov.mikhail/common/delimiter.cpp
  kostyukov.mikhail/common/delimiter.hpp
  kostyukov.mikhail/common/scopeGuard.cpp
  kostyukov.mikhail/common/scopeGuard.hpp
Labels: fine, new gr 5

#228 kazak.egor/T3
  kazak.egor/T3/commands.cpp
  kazak.egor/T3/commands.hpp
  kazak.egor/T3/main.cpp
  kazak.egor/T3/point.cpp
  kazak.egor/T3/point.hpp
  kazak.egor/T3/polygon.cpp
  kazak.egor/T3/polygon.hpp
  kazak.egor/T3/utils.cpp
  kazak.egor/T3/utils.hpp
Labels: fine, trash, new gr 4

#194 Brevnov.nikita/t3
  brevnov.nikita/T2/data_struct.cpp
  brevnov.nikita/T2/data_struct.hpp
  brevnov.nikita/T3/commands.cpp
  brevnov.nikita/T3/commands.hpp
  brevnov.nikita/T3/main.cpp
  brevnov.nikita/T3/polygon.cpp
  brevnov.nikita/T3/polygon.hpp
  brevnov.nikita/common/delimeters.cpp
  brevnov.nikita/common/delimeters.hpp
  brevnov.nikita/common/streamGuard.cpp
  brevnov.nikita/common/streamGuard.hpp
Labels: fine, gr 5, comedy artist

#232 zakirov.marat/T3
  zakirov.marat/T2/processing_structures.cpp
  zakirov.marat/T3/area_processing.cpp
  zakirov.marat/T3/area_processing.hpp
  zakirov.marat/T3/extremum_processing.cpp
  zakirov.marat/T3/extremum_processing.hpp
  zakirov.marat/T3/geometric_shape.cpp
  zakirov.marat/T3/geometric_shape.hpp
  zakirov.marat/T3/main.cpp
  zakirov.marat/T3/utilities.cpp
  zakirov.marat/T3/utilities.hpp
  zakirov.marat/T3/vertex_processing.cpp
  zakirov.marat/T3/vertex_processing.hpp
  zakirov.marat/common/stream_guardian.cpp
  zakirov.marat/common/stream_guardian.hpp
Labels: gr 4, trash

#179 petrov.nikita/T3
  petrov.nikita/T3/commands.cpp
  petrov.nikita/T3/commands.hpp
  petrov.nikita/T3/geometric_shapes.hpp
  petrov.nikita/T3/io_polygon.cpp
  petrov.nikita/T3/io_polygon.hpp
  petrov.nikita/T3/main.cpp
Labels: fine, gr 1

#206 mozhegova.maria/T3
  mozhegova.maria/T2/dataStruct.cpp
  mozhegova.maria/T3/commands.cpp
  mozhegova.maria/T3/commands.hpp
  mozhegova.maria/T3/main.cpp
  mozhegova.maria/T3/shapes.cpp
  mozhegova.maria/T3/shapes.hpp
  mozhegova.maria/common/delimiter.cpp
  mozhegova.maria/common/delimiter.hpp
  mozhegova.maria/common/scopeGuard.cpp
  mozhegova.maria/common/scopeGuard.hpp
Labels: fine, gr 1

#244 savintsev.ilya/F0
  savintsev.ilya/F0/confirmation-src.cpp
  savintsev.ilya/F0/confirmation-src.hpp
  savintsev.ilya/F0/file-system.cpp
  savintsev.ilya/F0/file-system.hpp
  savintsev.ilya/F0/main.cpp
  savintsev.ilya/F0/project-body.hpp
  savintsev.ilya/F0/project-cmds.cpp
  savintsev.ilya/F0/project-cmds.hpp
  savintsev.ilya/F0/renderer.hpp
  savintsev.ilya/common/base-types.cpp
  savintsev.ilya/common/base-types.hpp
  savintsev.ilya/common/complexquad.cpp
  savintsev.ilya/common/complexquad.hpp
  savintsev.ilya/common/concave.cpp
  savintsev.ilya/common/concave.hpp
  savintsev.ilya/common/geometry-utils.cpp
  savintsev.ilya/common/geometry-utils.hpp
  savintsev.ilya/common/rectangle.cpp
  savintsev.ilya/common/rectangle.hpp
  savintsev.ilya/common/shape-utils.cpp
  savintsev.ilya/common/shape-utils.hpp
  savintsev.ilya/common/shape.cpp
  savintsev.ilya/common/shape.hpp
Labels: fine, gr 4

#238 maslov.aleksey/F0
  maslov.aleksey/F0/commands.cpp
  maslov.aleksey/F0/commands.hpp
  maslov.aleksey/F0/main.cpp
Labels: fine, gr 1

#211 smirnov.vladislav/T3
  smirnov.vladislav/T3/commands.cpp
  smirnov.vladislav/T3/commands.hpp
  smirnov.vladislav/T3/geometry.cpp
  smirnov.vladislav/T3/geometry.hpp
  smirnov.vladislav/T3/main.cpp
Labels: fine, trash, new gr 5

#225 dribas.sergey/F0
  dribas.sergey/F0/commands.cpp
  dribas.sergey/F0/commands.hpp
  dribas.sergey/F0/main.cpp
  dribas.sergey/F0/race_predictor.cpp
  dribas.sergey/F0/race_predictor.hpp
  dribas.sergey/F0/rest_time.cpp
  dribas.sergey/F0/rest_time.hpp
  dribas.sergey/F0/survival.cpp
  dribas.sergey/F0/survival.hpp
  dribas.sergey/F0/workout.cpp
  dribas.sergey/F0/workout.hpp
Labels: gr 5

#234 abramov.vladislav/F0
  abramov.vladislav/F0/commands.cpp
  abramov.vladislav/F0/commands.hpp
  abramov.vladislav/F0/dictionary.cpp
  abramov.vladislav/F0/dictionary.hpp
  abramov.vladislav/F0/dictionary_collection.cpp
  abramov.vladislav/F0/dictionary_collection.hpp
  abramov.vladislav/F0/main.cpp
Labels: fine, gr 4

#235 duhanina.alina/F0
  duhanina.alina/F0/functor.cpp
  duhanina.alina/F0/functor.hpp
  duhanina.alina/F0/main.cpp
  duhanina.alina/F0/shannonFano.cpp
  duhanina.alina/F0/shannonFano.hpp
  duhanina.alina/F0/wrapper.cpp
  duhanina.alina/F0/wrapper.hpp
  duhanina.alina/T3/commands.cpp
  duhanina.alina/T3/commands.hpp
  duhanina.alina/T3/main.cpp
  duhanina.alina/T3/point.cpp
  duhanina.alina/T3/point.hpp
  duhanina.alina/T3/polygon.cpp
  duhanina.alina/T3/polygon.hpp
  duhanina.alina/common/dataStruct.cpp
  duhanina.alina/common/dataStruct.hpp
Labels: fine, gr 5, comedy artist

#243 fedorov.oleg/F0
  fedorov.oleg/F0/CommandHandler.cpp
  fedorov.oleg/F0/CommandHandler.hpp
  fedorov.oleg/F0/DictOperations.cpp
  fedorov.oleg/F0/HashTable.cpp
  fedorov.oleg/F0/HashTable.hpp
  fedorov.oleg/F0/ImportDictParsers.cpp
  fedorov.oleg/F0/ImportDictParsers.hpp
  fedorov.oleg/F0/ServiceOperations.cpp
  fedorov.oleg/F0/TextOperations.cpp
  fedorov.oleg/F0/TextProcessor.cpp
  fedorov.oleg/F0/TextProcessor.hpp
  fedorov.oleg/F0/Tokenizer.cpp
  fedorov.oleg/F0/Tokenizer.hpp
  fedorov.oleg/F0/Utility.cpp
  fedorov.oleg/F0/Utility.hpp
  fedorov.oleg/F0/ValidationUtils.cpp
  fedorov.oleg/F0/ValidationUtils.hpp
  fedorov.oleg/F0/main.cpp
Labels: trash, new gr 6, comedy artist

#177 drai.mohamedamine/T3
  drai.mohamedamine/T3/commands.cpp
  drai.mohamedamine/T3/commands.hpp
  drai.mohamedamine/T3/main.cpp
  drai.mohamedamine/T3/polygon.cpp
  drai.mohamedamine/T3/polygon.hpp
Labels: fine, new gr 5, comedy artist

#186 puzikov.herman/T3
  puzikov.herman/T2/data_struct.cpp
  puzikov.herman/T2/output_wrapper_structs.cpp
  puzikov.herman/T3/command_handler.cpp
  puzikov.herman/T3/command_handler.hpp
  puzikov.herman/T3/commands.cpp
  puzikov.herman/T3/commands.hpp
  puzikov.herman/T3/functional.cpp
  puzikov.herman/T3/functional.hpp
  puzikov.herman/T3/main.cpp
  puzikov.herman/T3/polygon.cpp
  puzikov.herman/T3/polygon.hpp
  puzikov.herman/common/format_guard.cpp
  puzikov.herman/common/format_guard.hpp
  puzikov.herman/common/input_wrapper_structs.cpp
  puzikov.herman/common/input_wrapper_structs.hpp
Labels: trash, new gr 6, comedy artist
