Repository Volgarenok/spbspu-labs-2025-tp-a, pull requests merged in 2025-09, with the labels that each got.

#141 krylov.matvey/T2
  krylov.matvey/T2/dataStruct.cpp
  krylov.matvey/T2/dataStruct.hpp
  krylov.matvey/T2/main.cpp
  krylov.matvey/common/delimeterIO.cpp
  krylov.matvey/common/delimeterIO.hpp
  krylov.matvey/common/streamGuard.cpp
  krylov.matvey/common/streamGuard.hpp
Labels: fine, gr 4

#236 averenkov.eugene/T3
  averenkov.eugene/T3/commands.cpp
  averenkov.eugene/T3/commands.hpp
  averenkov.eugene/T3/main.cpp
  averenkov.eugene/T3/polygon.cpp
  averenkov.eugene/T3/polygon.hpp
Labels: gr 5, dimkashelk

#269 nikitin.nickolai/T0
  nikitin.nickolai/T0/main.cpp
Labels: fine, new gr 6

#182 trukhanov.mikhail/T3
  trukhanov.mikhail/T2/data_struct.cpp
  trukhanov.mikhail/T3/commands.cpp
  trukhanov.mikhail/T3/commands.hpp
  trukhanov.mikhail/T3/main.cpp
  trukhanov.mikhail/T3/polygon.cpp
  trukhanov.mikhail/T3/polygon.hpp
  trukhanov.mikhail/T3/polygon_utils.cpp
  trukhanov.mikhail/T3/polygon_utils.hpp
  trukhanov.mikhail/common/data_input.cpp
  trukhanov.mikhail/common/data_input.hpp
  trukhanov.mikhail/common/stream_guard.cpp
  trukhanov.mikhail/common/stream_guard.hpp
Labels: fine, new gr 6, comedy artist

#204 pilugina.margarita/T3
  pilugina.margarita/T2/data_struct.cpp
  pilugina.margarita/T2/format_wrapper.cpp
  pilugina.margarita/T2/format_wrapper.hpp
  pilugina.margarita/T2/main.cpp
  pilugina.margarita/T2/utils.cpp
  pilugina.margarita/T3/areaCommands.cpp
  pilugina.margarita/T3/areaCommands.hpp
  pilugina.margarita/T3/commands.cpp
  pilugina.margarita/T3/commands.hpp
  pilugina.margarita/T3/countCommands.cpp
  pilugina.margarita/T3/countCommands.hpp
  pilugina.margarita/T3/extraCommands.cpp
  pilugina.margarita/T3/extraCommands.hpp
  pilugina.margarita/T3/extraPerimeterCommands.cpp
  pilugina.margarita/T3/extraPerimeterCommands.hpp
  pilugina.margarita/T3/main.cpp
  pilugina.margarita/T3/maxCommands.cpp
  pilugina.margarita/T3/maxCommands.hpp
  pilugina.margarita/T3/minCommands.cpp
  pilugina.margarita/T3/minCommands.hpp
  pilugina.margarita/T3/polygon.cpp
  pilugina.margarita/T3/polygon.hpp
  pilugina.margarita/common/delimiterIO.cpp
  pilugina.margarita/common/delimiterIO.hpp
  pilugina.margarita/common/format_guard.cpp
  pilugina.margarita/common/format_guard.hpp
Labels: new gr 6, dimkashelk

#201 shak.vitalina/T3
  shak.vitalina/T2/data_struct.cpp
  shak.vitalina/T2/input.cpp
  shak.vitalina/T3/commands.cpp
  shak.vitalina/T3/commands.hpp
  shak.vitalina/T3/main.cpp
  shak.vitalina/T3/polygon.cpp
  shak.vitalina/T3/polygon.hpp
  shak.vitalina/common/delimiter.cpp
  shak.vitalina/common/delimiter.hpp
  shak.vitalina/common/stream_guard.cpp
  shak.vitalina/common/stream_guard.hpp
Labels: new gr 6

#168 filonova.angelina/T3
  filonova.angelina/T3/commands.cpp
  filonova.angelina/T3/commands.hpp
  filonova.angelina/T3/main.cpp
  filonova.angelina/T3/polygon.cpp
  filonova.angelina/T3/polygon.hpp
  filonova.angelina/common/format_guard.cpp
  filonova.angelina/common/format_guard.hpp
  filonova.angelina/common/input_struct.cpp
  filonova.angelina/common/input_struct.hpp
Labels: fine, new gr 6, dimkashelk

#207 filonova.angelina/F0
  filonova.angelina/F0/commands.cpp
  filonova.angelina/F0/commands.hpp
  filonova.angelina/F0/main.cpp
  filonova.angelina/F0/support.cpp
  filonova.angelina/F0/support.hpp
Labels: new gr 6

#181 aleksandrov.igor/T3
  aleksandrov.igor/T3/geometry.cpp
  aleksandrov.igor/T3/geometry.hpp
  aleksandrov.igor/T3/main.cpp
  aleksandrov.igor/T3/polygon-commands.cpp
  aleksandrov.igor/T3/polygon-commands.hpp
  aleksandrov.igor/common/data-struct.hpp
  aleksandrov.igor/common/input-struct.cpp
  aleksandrov.igor/common/input-struct.hpp
  aleksandrov.igor/common/stream-guard.cpp
  aleksandrov.igor/common/stream-guard.hpp
Labels: fine, gr 4, dimkashelk, rail

#189 voronina.nadia/T3
  voronina.nadia/T2/DataStruct.cpp
  voronina.nadia/T2/DataStruct.h
  voronina.nadia/T3/Commands.cpp
  voronina.nadia/T3/Commands.h
  voronina.nadia/T3/FillVectorOfShapes.cpp
  voronina.nadia/T3/FillVectorOfShapes.h
  voronina.nadia/T3/Shapes.cpp
  voronina.nadia/T3/Shapes.h
  voronina.nadia/T3/Subcommands.cpp
  voronina.nadia/T3/Subcommands.h
  voronina.nadia/T3/main.cpp
  voronina.nadia/common/Delimiter.cpp
  voronina.nadia/common/Delimiter.h
  voronina.nadia/common/IOFmtguard.cpp
  voronina.nadia/common/IOFmtguard.h
Labels: new gr 4

#153 Smirnov.dmitriy/t2
  smirnov.dmitriy/T2/datastruct.cpp
  smirnov.dmitriy/T2/datastruct.hpp
  smirnov.dmitriy/T2/delimiter.cpp
  smirnov.dmitriy/T2/delimiter.hpp
  smirnov.dmitriy/T2/input.txt
  smirnov.dmitriy/T2/main.cpp
  smirnov.dmitriy/T2/scopeguard.cpp
  smirnov.dmitriy/T2/scopeguard.hpp
  smirnov.dmitriy/T2/value.cpp
  smirnov.dmitriy/T2/value.hpp
Labels: new gr 4

#164 kushekbaev.danil/T3
  kushekbaev.danil/T2/datastruct.cpp
  kushekbaev.danil/T2/datastruct.hpp
  kushekbaev.danil/T2/main.cpp
  kushekbaev.danil/T3/commands.cpp
  kushekbaev.danil/T3/commands.hpp
  kushekbaev.danil/T3/main.cpp
  kushekbaev.danil/T3/polygon.cpp
  kushekbaev.danil/T3/polygon.hpp
  kushekbaev.danil/common/delimiter.cpp
  kushekbaev.danil/common/delimiter.hpp
Labels: gr 4, black mark, comedy artist, dimkashelk

#139 ageev.ilya/T2
  ageev.ilya/T2/DataStruct.cpp
  ageev.ilya/T2/DataStruct.hpp
  ageev.ilya/T2/main.cpp
Labels: comedy artist

#116 asafov.andrew/T2
  asafov.andrew/T2/compareDataStruct.cpp
  asafov.andrew/T2/datastruct.h
  asafov.andrew/T2/inputDataStruct.cpp
  asafov.andrew/T2/main.cpp
  asafov.andrew/T2/outputDataStruct.cpp
  asafov.andrew/common/streamGuard.cpp
  asafov.andrew/common/streamGuard.h
Labels: gr 4

#249 orlova.alena/F0
  orlova.alena/F0/commands.cpp
  orlova.alena/F0/commands.h
  orlova.alena/F0/details.cpp
  orlova.alena/F0/details.h
  orlova.alena/F0/io-utils.cpp
  orlova.alena/F0/io-utils.h
  orlova.alena/F0/main.cpp
Labels: fine, new gr 4

#252 averenkov.eugene/F0
  averenkov.eugene/F0/base.cpp
  averenkov.eugene/F0/base.hpp
  averenkov.eugene/F0/commands.cpp
  averenkov.eugene/F0/commands.hpp
  averenkov.eugene/F0/item.cpp
  averenkov.eugene/F0/item.hpp
  averenkov.eugene/F0/kit.cpp
  averenkov.eugene/F0/kit.hpp
  averenkov.eugene/F0/knapsack.cpp
  averenkov.eugene/F0/knapsack.hpp
  averenkov.eugene/F0/main.cpp
  averenkov.eugene/F0/solves.cpp
  averenkov.eugene/F0/solves.hpp
Labels: gr 5

#245 fedorova.ksenia/T3
  fedorova.ksenia/T2/DataStruct.cpp
  fedorova.ksenia/T2/DataStruct.h
  fedorova.ksenia/T3/commands.cpp
  fedorova.ksenia/T3/commands.h
  fedorova.ksenia/T3/geom.cpp
  fedorova.ksenia/T3/geom.h
  fedorova.ksenia/T3/main.cpp
  fedorova.ksenia/common/delimiter.cpp
  fedorova.ksenia/common/delimiter.h
  fedorova.ksenia/common/io-guard.cpp
  fedorova.ksenia/common/io-guard.h
Labels: fine, dimkashelk

#265 krylov.matvey/T3
  krylov.matvey/T3/commands.cpp
  krylov.matvey/T3/commands.hpp
  krylov.matvey/T3/geometry.cpp
  krylov.matvey/T3/geometry.hpp
  krylov.matvey/T3/main.cpp
Labels: fine, gr 4

#275 nikonov.andrew/T3
  nikonov.andrew/T2/DataStruct.cpp
  nikonov.andrew/T2/IOUtilities.cpp
  nikonov.andrew/T2/IOUtilities.hpp
  nikonov.andrew/T3/commands.cpp
  nikonov.andrew/T3/commands.hpp
  nikonov.andrew/T3/geom.cpp
  nikonov.andrew/T3/geom.hpp
  nikonov.andrew/T3/main.cpp
  nikonov.andrew/common/DelimetrIO.cpp
  nikonov.andrew/common/DelimetrIO.hpp
  nikonov.andrew/common/StreamGuard.cpp
  nikonov.andrew/common/StreamGuard.hpp
Labels: gr 4, trash

#224 mazitov.vladislav/T3
  mazitov.vladislav/T2/data_struct.cpp
  mazitov.vladislav/T2/input_struct.cpp
  mazitov.vladislav/T2/input_struct.hpp
  mazitov.vladislav/T2/stream_guard.cpp
  mazitov.vladislav/T2/stream_guard.hpp
  mazitov.vladislav/T3/area_commands.cpp
  mazitov.vladislav/T3/area_commands.hpp
  mazitov.vladislav/T3/commands.cpp
  mazitov.vladislav/T3/commands.hpp
  mazitov.vladislav/T3/count_commands.cpp
  mazitov.vladislav/T3/count_commands.hpp
  mazitov.vladislav/T3/intersections_command.cpp
  mazitov.vladislav/T3/intersections_command.hpp
  mazitov.vladislav/T3/main.cpp
  mazitov.vladislav/T3/max_commands.cpp
  mazitov.vladislav/T3/max_commands.hpp
  mazitov.vladislav/T3/min_commands.cpp
  mazitov.vladislav/T3/min_commands.hpp
  mazitov.vladislav/T3/polygon.cpp
  mazitov.vladislav/T3/polygon.hpp
  mazitov.vladislav/T3/rm_echo_command.cpp
  mazitov.vladislav/T3/rm_echo_command.hpp
  mazitov.vladislav/common/delimiter.cpp
  mazitov.vladislav/common/delimiter.hpp
  mazitov.vladislav/common/format_guard.cpp
  mazitov.vladislav/common/format_guard.hpp
Labels: trash, new gr 6

#240 smirnov.alexandr/T3
  smirnov.alexandr/T2/data_struct.cpp
  smirnov.alexandr/T2/data_struct.hpp
  smirnov.alexandr/T3/commands.cpp
  smirnov.alexandr/T3/commands.hpp
  smirnov.alexandr/T3/main.cpp
  smirnov.alexandr/T3/polygon.cpp
  smirnov.alexandr/T3/polygon.hpp
  smirnov.alexandr/common/delimetr.cpp
  smirnov.alexandr/common/delimetr.hpp
Labels: gr 1, dimkashelk

#278 holodilov.artem/T3
  holodilov.artem/T3/commands.cpp
  holodilov.artem/T3/commands.hpp
  holodilov.artem/T3/main.cpp
  holodilov.artem/T3/polygon.cpp
  holodilov.artem/T3/polygon.hpp
  holodilov.artem/T3/subcommands.cpp
  holodilov.artem/T3/subcommands.hpp
  holodilov.artem/common/DelimIO.cpp
  holodilov.artem/common/DelimIO.hpp
  holodilov.artem/common/ScopeGuard.cpp
  holodilov.artem/common/ScopeGuard.hpp
Labels: fine, new gr 5, dimkashelk
